### ISSUE TITLE
Allow one level of indirection so variables declared elsewhere do not fail

### ISSUE THREAD

**Issue by lee-chase** [lee-chase/carbon-use#2]
The current linter relies on locally declared variables. 

Add the following accept case to https://github.com/lee-chase/carbon-use/blob/master/src/rules/theme-token-use/__tests__/parseOptions.test.js

```css
    {
      code: "@import './test'; .foo { color: $a-carbon-token; }",
      description: "Carbon theme token when imported.",
    },
```

Create a file that looks like this
```css
@import "@carbon/themes";
$a-non-carbon-token: #fefefe;
$a-carbon-token: $ui-01;
```

Make the test pass by updating the rule https://github.com/lee-chase/carbon-use/blob/master/src/rules/theme-token-use/index.js

NOTE: Do not fix by ignoring unknown variable declarations ;-)
